version: '3'
services:
  mongodb:
    image: bitnami/mongodb:4.1.3
    environment:
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_USERNAME=aaa
      - MONGODB_PASSWORD=123456
      - MONGODB_DATABASE=aaa
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/bitnami
  radiks_server:
    build:
      context: ./
      dockerfile: radiks-dockerfile
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "radiks-server"]
    volumes:
      - ./:/app/
    environment:
      - MONGODB_URI="mongodb://root:123456@mongodb:27017"
    ports:
      - 1260:1260

